export const PathConstants = {
  LOGIN: "/login",
  REGISTER: "/register",
  LOGOUT: "logout",
  VERIFICATION: "/verification",
  DASHBOARD: "/",
  CALENDAR: "",
  TERMS: "/terms",
  PRIVACY: "/privacy",
  SETTINGS: "/settings",
  BUSINESS: "business",
  FORGET_PASS: "/forget-password",
  RESETPASSWORD: "/reset-password",
  ONBOARDING: "/onboarding",
  STEP1: "steps/01",
  STEP2: "steps/02",
  STEP3: "steps/03",
  STEP4: "steps/04",
  WEEK: "week",
};
