export const PathConstants = {
  LOGIN: "/login",
  REGISTER: "/register",
  LOGOUT: "logout",
  VERIFICATION: "/verification",
  DASHBOARD: "/",
  CALENDAR: "",
  TERMS: "/terms",
  PRIVACY: "/privacy",
  SETTINGS: "/settings",
  BUSINESS: "business",
  FORGETPASS: "/forget-password",
  RESETPASSWORD: "/reset-password",
  ONBOARDING: "/onboarding",
  STEP1: "step01",
  STEP2: "step02",
  STEP3: "step03",
  STEP4: "step04",
  WEEK: "week",
};
